# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  print_pipeline_id:
    # description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: $CIRCLE_WORKFLOW_ID
    steps:
      - run: echo << parameters.to >>
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

# Here the start of the exercise from the course:
jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:2020.01
    steps:
      - print_pipeline_id


  # save_hello_world_output:
  #   docker:
  #     - image: cimg/base:2020.01
  #   steps:
  #     # - checkout:
  #     - run: 
  #         name: "Save text into file."
  #         command: |
  #           echo "hello world" > /tmp/output.txt
  #     - persist_to_workspace:
  #         root: /tmp/
  #         paths:
  #           - output.txt

  # print_output_file:
  #   docker:
  #     - image: cimg/base:2020.01
  #   steps:
  #     # - checkout:
  #     - attach_workspace:
  #         at: /tmp/
  #     - run: 
  #         name: "Cat txt from file."
  #         command: |
  #           cat /tmp/output.txt

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - save_hello_world_output
      # - save_hello_world_output
      # - print_output_file:
      #     requires:
      #       - save_hello_world_output